language: c
dist: xenial
sudo: false
branches:
  only:
  - master
  # Tags
  - /^(\d+\.)+\d+(\.\S+)?$/

compiler:
  - clang
  - gcc

cache:
  apt: true
  pip: true

addons:
  apt:
    packages:
      - python-pip
      - cppcheck
      - libwnck-3-dev
      - libglib2.0-dev
      - groff

before_install:
  - set -e
  - pip install --user cpplint
  - ./lint.sh
  - "! groff -wall -mandoc -Thtml doc/xsuspender.1 |& grep ' warning: '"

install:
  - cd build
  - DISPLAY=mock-for-later cmake -DCMAKE_C_FLAGS=-Werror -DCMAKE_INSTALL_PREFIX=~ ..
  - make
  - make install
  - cpack

script:
  - xvfb-run make test

after_success:
  - if [ "$TRAVIS_BRANCH" = "$TRAVIS_TAG" ] && [ $CC = "gcc" ]; then cd ..; .travis/deploy-gh-pages.sh; fi
