language: c
dist: trusty
sudo: false

compiler:
  - clang
  - gcc

cache:
  apt: true
  pip: true

addons:
  apt:
    packages:
      - python-pip
      - cppcheck
      - libwnck-3-dev
      - libglib2.0-dev

before_install:
  - set -e
  - pip install --user cpplint
  - ./lint.sh

install:
  - cd build
  - DISPLAY=mock-for-later cmake -DCMAKE_C_FLAGS=-Werror -DCMAKE_INSTALL_PREFIX=~ ..
  - make
  - make install
  - cpack

script:
  - xvfb-run make test
