name: CI
on:
  push: { branches: [master] }
  pull_request: { branches: [master] }
  schedule: [ cron: '3 15 * * 6' ]  # Every Saturday, 03:15

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install cppcheck groff python3-wheel
      - run: pip3 install --user cpplint
      - run: ./lint.sh
      - run: |
          ! groff -wall -mandoc -Thtml doc/xsuspender.1 |& grep ' warning: '

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install libglib2.0-dev libwnck-3-dev procps make cmake pkg-config
      - env:
          CC: ${{ matrix.compiler }}
          DISPLAY: mock-for-later
        run: |
          cd build
          cmake -DCMAKE_C_FLAGS=-Werror -DCMAKE_INSTALL_PREFIX=~ ..
          make
          make install
          cpack
          xvfb-run make test
