on:
  push:
    tags: ['[0-9]+.[0-9]+*']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install groff
      - env:
          GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: .github/deploy-gh-pages.sh
